name: bloc_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">= 3.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  get_it: ^7.6.4
  injectable: ^2.3.2
  drift: ^2.30.1
  path_provider: ^2.1.3
  sqlite3_flutter_libs: ^0.5.5
  bloc: ^9.2.0
  test_track: ^0.3.3
  bloc_test: ^10.0.0
  dcm: ^1.8.1
  formz: ^0.4.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  flutter_lints: ^3.0.1
  drift_dev: ^2.30.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true