name: Flutter CI + Codacy

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.38.9
          cache: true

      - name: Pub get
        run: flutter pub get

      - name: Code generation
        run: |
          flutter pub run build_runner build \
            --delete-conflicting-outputs

      - name: Flutter analyze
        run: flutter analyze

      - name: Install Codacy CLI v2
        run: |
          curl -Ls https://raw.githubusercontent.com/codacy/codacy-cli-v2/main/codacy-cli.sh -o codacy-cli.sh
          chmod +x codacy-cli.sh

      - name: Codacy install runtimes/tools
        run: ./codacy-cli.sh install

      - name: Run dartanalyzer (SARIF)
        run: ./codacy-cli.sh analyze -t dartanalyzer --format sarif -o dartanalyzer.sarif

      - name: Upload report to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: ./codacy-cli.sh upload -s dartanalyzer.sarif -c ${{ github.sha }} -t "$CODACY_PROJECT_TOKEN"
